### ISSUE TITLE
Lesti cache compatibillity

### ISSUE THREAD

**Issue by danielchicote** [tzyganu/EasylifeTag#11]
Hello, im using lesti cache but with the easylife module it don't refresh the tags page, and always give the same page with the first served content.

I have put "tag/^[0-9a-z_]+$/," as  Miss Uri Params, "tag" as uri params, and "tag_products" as lazy block, but the cache always serve the first listed page.

¿Do you have used easylifetag module with lesti cache or other cache module? ¿How?

**Comment by tzyganu** [comment]
@danielchicote Sorry, but I cannot make this compatible with every extension that exists. I have no idea how Lesti cache works.
