### ISSUE TITLE
it doesn´t work

### ISSUE THREAD

**Issue by ghost** [tzyganu/EasylifeTag#3]
Hi,
the extension is not working. The folder is in app/code/community/Easylife/Tag/ and the file app/etc/module/Easylife_Tag.xml, the cache is empty an the indexes are new.
What can i do?
please see: www.gesundwuerzen.de

**Comment by ghost** [comment]
sorry, there was no folder: Model in community. Now it´s working great.

**Comment by ghost** [comment]
oh no. There is problem with blanks and umlaut mark in the url.

**Comment by tzyganu** [comment]
@solarlaus can you be more specific? "Doesn't work" means a lot and nothing at the same time. Give some examples. Some screenshots could help. help me help you.

**Comment by ghost** [comment]
Hi,

please read my last post...

**Comment by tzyganu** [comment]
@solarlaus. I did. but please provide one tag that does not work, or a screenshot of what you see, or both. It will help me a lot.

**Comment by tzyganu** [comment]
@solarlaus the umlaut problem should be fixed in version 1.0.0.

**Comment by ghost** [comment]
very nice! it´s work fine
thank you
