### ISSUE TITLE
Adding new tag 404 NOT FOUND

### ISSUE THREAD

**Issue by arisdario** [tzyganu/EasylifeTag#4]
Hello Marius, i would like to know if is there an option to create the rewrite automatically on add a new tag, every time is added a new tag need to be created manually in the url rewrite management.

Thanks

**Comment by tzyganu** [comment]
@arisdario This extension does not involve url  rewrites. It just has a custom router that tries to find a certain tag based on an url key. Are you sure the tag you add is active on the current store and is enabled?. I'm not able to reproduce this issue.

**Comment by arisdario** [comment]
The idea is that, by installing the module will change all tags to "tag/name-tag" so we need to create the custom url rewrite for each one to get working properly in the frontend, otherwise it will remain as "tag/name-tag" and the page will show "404 Not Found", so, on add a new tag "new-tag" it will be enabled, active, showing in the frontend as "tag/new-tag" not as "tag/list/tagid/x/", if the rewrite url is not created it will not route to list products by "new-tag" it will show "404 Not Found"

Thanks,

**Comment by tzyganu** [comment]
Sorry but I don't understand. It may be the "christmassy" mood, or something else, but I'm not getting it at all.  Can you provide some screenshots of what's happening when you get 404 pages?

**Comment by tzyganu** [comment]
Closed due to inactivity
