### ISSUE TITLE
Multiple Tags

### ISSUE THREAD

**Issue by fschleifenbaum** [tzyganu/EasylifeTag#5]
Wow this is Gold! Thank you very much! I have one question: Is it possible to display multiple tags, like url.com/tag/tag-1+tag-2 or even better url.com/tagged/tag-1/tag-2?

**Comment by tzyganu** [comment]
@fschleifenbaum No it's not possible. And is not in the scope of this extension. The only thing the extension does is to allow SEF URLs for tag pages.
