### ISSUE TITLE
2 words Tags in URL

### ISSUE THREAD

**Issue by sallygny** [tzyganu/EasylifeTag#6]
Hi,
Great extension!
One thing though .... for 2 words tags, the URL looks like this "mydomain/tag/My Tag" in firefox (with a space between the words) and "mydomain/tag/My%20%Tag" in IE. Is there a way to connect the 2 words in the urls with a separator like "-" or "_" ?!?
If so, what needs to be changed and where?

Thanks a bunch

**Comment by tzyganu** [comment]
@sallygny It's not possible through the extension. and I don't intend to implement it either.
