### ISSUE TITLE
tag/product/list/tagId/10 to tag/clothes/

### ISSUE THREAD

**Issue by 4bedah** [tzyganu/EasylifeTag#9]
Hi,

is it possible to change the rewrite to tag/xxx/ with the close"/" ?
I have test some changes but it dont run.
Now i have a 301 rewrite but this is not optimal. 

Thanks Nico

**Comment by tzyganu** [comment]
@4bedah You can try by changing this line: https://github.com/tzyganu/EasylifeTag/blob/master/app/code/community/Easylife/Tag/Model/Tag.php#L26 to `return Mage::getUrl('', array('_direct' => 'tag/'.$this->getName().'/'));`.  
Let me know if it works.

**Comment by 4bedah** [comment]
Hi, thanks! It works fin!
my finally line:  
`return Mage::getUrl('', array('_direct' => 'tag/'.str_replace(" ", "_", $this->getName().'/')));`

Whitout '.str_replace xxx i get a 404 error with 2 words. The same is if i change "_" to "-" - but so is it okay for me.

Thanks!
